# Generated by Django 4.1.1 on 2022-09-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reservableitem_reservationitemdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='status',
            field=models.CharField(blank=True, choices=[['requested', 'Requested'], ['rejected', 'Rejected']], max_length=20, null=True),
        ),
    ]
