# Generated by Django 4.1.1 on 2022-09-11 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_activity_car_stay_delete_cars_delete_stays'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
