# Generated by Django 4.1.1 on 2022-09-12 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_carres'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[['car', 'Car'], ['rental', 'Rental'], ['activity', 'Activity']], max_length=20)),
                ('base_price', models.FloatField()),
                ('is_available', models.BooleanField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationItemData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('value', models.TextField()),
                ('order', models.IntegerField()),
                ('reservation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reservableitem')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationItemMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cover', models.BooleanField()),
                ('file', models.FileField(upload_to='')),
                ('type', models.CharField(choices=[['image', 'Image'], ['videos', 'Video']], max_length=20)),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('order', models.IntegerField()),
                ('reservation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reservableitem')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[['requested', 'Requested'], ['rejected', 'Rejected']], max_length=20)),
                ('reservation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reservableitem')),
                ('reservation_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.RemoveField(
            model_name='carres',
            name='car',
        ),
        migrations.RemoveField(
            model_name='carres',
            name='user',
        ),
        migrations.DeleteModel(
            name='Stay',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='CarRes',
        ),
    ]
